development:
  adapter: postgresql
  database: travelpoker_development
  host: localhost

test:
  adapter: postgresql
  database: travelpoker_test
  host: localhost

production:
  adapter: postgresql
  database: travelpoker_production
  host: localhost
